sudo: required

services:
  - docker

before-install:
  - docker build -t arun98/docker-react -f Dockerfile .

script:
  - docker run -e CI=true arun98/docker-react npm run test

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-ap-south-1-919723724666"
  bucket-path: "Docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
after_deploy:
  - ./after_deploy_1.sh
  - ./after_deploy_2.sh
