sudo: required

services:
  - docker

before-install:
  - docker build -t arun98/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arun98/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-2-919723724666"
  bucket-path: "Docker-react"
  on:
    branch: main
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
